package idx

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"io"
)

// Header layout, page 0, verified 2026-07-23 against a .IDX file
// generated by Clipper's DBFCDX driver (docs/RESEARCH_NOTES.md
// finding 2):
//
//	offset  size  contents                        observed
//	 0– 3    4    root node pointer                1024
//	 4– 7    4    free list pointer                 0
//	 8–11    4    end-of-file pointer                0
//	12–13    2    key length                        10
//	14       1    index options                     0x20 (compact)
//	15       1    index signature                    0
//	16–235  220   key expression, NUL-terminated
//	236–455 220   FOR expression, NUL-terminated
//	456–511  56   reserved
const (
	offRoot    = 0
	offFree    = 4
	offEOF     = 8
	offKeyLen  = 12
	offOpts    = 14
	offSig     = 15
	offKeyExpr = 16
	keyExprLen = 220
)

func readHeader(r io.ReadSeeker) (*Index, error) {
	if _, err := r.Seek(0, io.SeekStart); err != nil {
		return nil, fmt.Errorf("idx: seek header: %w", err)
	}
	var raw [PageSize]byte
	if _, err := io.ReadFull(r, raw[:]); err != nil {
		return nil, fmt.Errorf("idx: read header: %w", err)
	}

	ix := &Index{
		root:    binary.LittleEndian.Uint32(raw[offRoot:]),
		free:    binary.LittleEndian.Uint32(raw[offFree:]),
		eof:     binary.LittleEndian.Uint32(raw[offEOF:]),
		keySize: binary.LittleEndian.Uint16(raw[offKeyLen:]),
		opts:    raw[offOpts],
	}
	tail := raw[offKeyExpr : offKeyExpr+keyExprLen]
	if end := bytes.IndexByte(tail, 0); end >= 0 {
		ix.keyExpr = string(tail[:end])
	} else {
		ix.keyExpr = string(tail)
	}

	if ix.opts&OptCompact == 0 {
		return nil, ErrNotCompact
	}
	if ix.keySize == 0 || ix.keySize > 240 {
		return nil, fmt.Errorf("%w: key length %d out of range", ErrInvalidHeader, ix.keySize)
	}
	return ix, nil
}

func (ix *Index) writeHeader() error {
	var raw [PageSize]byte
	binary.LittleEndian.PutUint32(raw[offRoot:], ix.root)
	binary.LittleEndian.PutUint32(raw[offFree:], ix.free)
	binary.LittleEndian.PutUint32(raw[offEOF:], ix.eof)
	binary.LittleEndian.PutUint16(raw[offKeyLen:], ix.keySize)
	raw[offOpts] = ix.opts
	expr := ix.keyExpr
	if len(expr) > keyExprLen-1 {
		expr = expr[:keyExprLen-1]
	}
	copy(raw[offKeyExpr:], expr)

	if _, err := ix.rw.Seek(0, io.SeekStart); err != nil {
		return fmt.Errorf("idx: seek header: %w", err)
	}
	_, err := ix.rw.Write(raw[:])
	return err
}
