package dbf

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
)

// TestFPTReadsClipperGeneratedFixture is the oracle byte-comparison
// test for T-12. The fixture (dbf/testdata/FDATA.{DBF,FPT}) was
// generated by Clipper 5.2e via DBFCDX.LIB — the same driver that
// closed T-01, T-02, and T-09 — with a schema containing a memo
// field and three records.
//
// This test asserts:
//
//   - The DBF version byte is 0xF5 (FPT-flavour) and blipper's
//     dbf.Open accepts it.
//   - Table.MemoFormat() reports MemoFormatFPT.
//   - The FPT block size is 64 (Clipper DBFCDX's default) and
//     the header's next-free pointer is 11 (verified by hand
//     against the raw bytes in FDATA.README.md).
//   - Memo pointers in the DBF records dereference to the correct
//     content via FPTFile.Get, exercising the corrected
//     block-numbering formula. Record 1's memo is at block 8
//     (not block 1) — this is the load-bearing correctness
//     property that the earlier implementation got wrong.
//   - Content matches byte-for-byte what CX.PRG wrote via
//     Clipper's REPLACE NOTES WITH ... calls.
func TestFPTReadsClipperGeneratedFixture(t *testing.T) {
	dbfPath := filepath.Join("testdata", "FDATA.DBF")
	fptPath := filepath.Join("testdata", "FDATA.FPT")

	dbfBytes, err := os.ReadFile(dbfPath)
	if err != nil {
		t.Fatalf("read %s: %v", dbfPath, err)
	}
	fptBytes, err := os.ReadFile(fptPath)
	if err != nil {
		t.Fatalf("read %s: %v", fptPath, err)
	}

	if dbfBytes[0] != 0xF5 {
		t.Fatalf("fixture DBF version byte = 0x%02X, want 0xF5", dbfBytes[0])
	}

	dbfBuf := &memFile{data: dbfBytes}
	tbl, err := Open(dbfBuf)
	if err != nil {
		t.Fatalf("Open FDATA.DBF: %v", err)
	}
	if got := tbl.MemoFormat(); got != MemoFormatFPT {
		t.Errorf("MemoFormat = %v, want MemoFormatFPT", got)
	}
	if got := tbl.RecordCount(); got != 3 {
		t.Errorf("RecordCount = %d, want 3", got)
	}

	fptBuf := &memFile{data: fptBytes}
	fpt, err := OpenFPT(fptBuf)
	if err != nil {
		t.Fatalf("OpenFPT FDATA.FPT: %v", err)
	}
	if got := fpt.BlockSize(); got != 64 {
		t.Errorf("BlockSize = %d, want 64 (Clipper DBFCDX default)", got)
	}
	if got := fpt.NextFree(); got != 11 {
		t.Errorf("NextFree = %d, want 11 (verified against raw bytes)", got)
	}

	// Read every record, resolve its memo pointer, verify content.
	// Expected values match CX.PRG's REPLACE calls verbatim.
	type expectation struct {
		code      string
		memoBlock uint32 // 0 for absent
		memoText  string
	}
	want := []expectation{
		{code: "ALPHA", memoBlock: 8, memoText: "hello world"},
		{code: "BRAVO", memoBlock: 9, memoText: "second memo, deliberately longer to span more than one 64-byte block. Padding padding padding."},
		{code: "CHARLIE", memoBlock: 0, memoText: ""},
	}
	for i, w := range want {
		rec, err := tbl.Get(uint32(i + 1))
		if err != nil {
			t.Fatalf("Get(%d): %v", i+1, err)
		}
		// Field 0 is CODE, field 1 is NOTES.
		codeVal, err := rec.Get(tbl.Schema(), "CODE")
		if err != nil {
			t.Fatalf("record %d CODE: %v", i+1, err)
		}
		if got := codeVal.(string); got != w.code {
			t.Errorf("record %d CODE = %q, want %q", i+1, got, w.code)
		}
		notesVal, err := rec.Get(tbl.Schema(), "NOTES")
		if err != nil {
			t.Fatalf("record %d NOTES: %v", i+1, err)
		}
		block, present, err := ParseMemoPointer([]byte(notesVal.(string)))
		if err != nil {
			t.Fatalf("record %d ParseMemoPointer: %v", i+1, err)
		}
		if !present {
			if w.memoBlock != 0 {
				t.Errorf("record %d memo absent, want block %d", i+1, w.memoBlock)
			}
			continue
		}
		if block != w.memoBlock {
			t.Errorf("record %d memo block = %d, want %d", i+1, block, w.memoBlock)
		}
		content, memoType, err := fpt.Get(block)
		if err != nil {
			t.Fatalf("record %d fpt.Get(%d): %v", i+1, block, err)
		}
		if memoType != MemoText {
			t.Errorf("record %d memo type = %d, want MemoText", i+1, memoType)
		}
		if !bytes.Equal(content, []byte(w.memoText)) {
			t.Errorf("record %d memo content mismatch:\n  got:  %q\n  want: %q",
				i+1, content, w.memoText)
		}
	}
}
