// Package ndx implements dBASE III+ compatible .NDX index files.
//
// An NDX file is a paged B-tree with 512-byte pages. Page 0 is the
// header — the anchor node — and every other page holds a count of
// live entries followed by an array of fixed-size key records.
//
// The layout is documented in docs/INDEX_FORMATS.md and was
// verified against files generated by Clipper 5.2e's DBFNDX driver
// under the oracle harness (docs/CLIPPER_ORACLE.md). Every header
// field, the key-record sizing rule, and the node entry layout
// matched on first decode for both a character and a numeric
// index.
//
// Two differences from the sibling ntx package are worth knowing:
//
//   - Pages are 512 bytes, not 1024.
//   - Numeric keys are stored as plain IEEE-754 doubles. The CDX
//     format applies a byte-reversal and bit-inversion transform so
//     that byte comparison yields numeric order; NDX does not, and
//     carrying that assumption across formats would corrupt
//     negative values only — the kind of partial correctness that
//     survives casual testing.
package ndx

import (
	"errors"
	"io"

	"github.com/ha1tch/blipper/dbf"
)

// PageSize is the fixed size of every page in an NDX file,
// including the header.
const PageSize = 512

// Key type codes stored at header offset 16.
const (
	// KeyTypeCharacter marks an index whose keys are byte strings
	// compared as unsigned bytes.
	KeyTypeCharacter uint16 = 0

	// KeyTypeNumeric marks an index whose keys are 8-byte IEEE-754
	// doubles.
	KeyTypeNumeric uint16 = 1
)

// MaxKeyExpr is the space available for the key expression in the
// header: from offset 24 to the end of the page.
const MaxKeyExpr = PageSize - 24

// MaxKeySize is the largest key this package will write. The
// format allows more in principle, but a key must leave room for
// at least two entries per page to keep the tree meaningful.
const MaxKeySize = 100

// Errors returned by this package.
var (
	// ErrInvalidHeader is returned when the anchor node does not
	// describe a usable index.
	ErrInvalidHeader = errors.New("ndx: invalid index header")

	// ErrCorrupt indicates a structural inconsistency: a page
	// pointer outside the file, an entry count beyond what a page
	// can hold, or a chain that loops.
	ErrCorrupt = errors.New("ndx: corrupt index structure")

	// ErrKeySize is returned when a key does not match the width
	// the index was created with. Keys are fixed-size; a caller
	// supplying the wrong length is a programming error rather
	// than a data condition.
	ErrKeySize = errors.New("ndx: key length does not match index")

	// ErrDuplicate is returned by Insert on a unique index when
	// the key is already present.
	ErrDuplicate = errors.New("ndx: duplicate key in unique index")
)

// KeyFunc derives the fixed-size index key bytes for a record.
//
// Mirrors ntx.KeyFunc deliberately: the two packages are used
// interchangeably by blipperdb, and a caller switching between
// index formats should not have to rewrite key derivation.
type KeyFunc func(dbf.Record) []byte

// Options describes a new index.
type Options struct {
	// KeyExpr is the dBASE key expression stored in the header,
	// for example "UPPER(NAME)". It documents how keys are
	// derived; this package does not evaluate it.
	KeyExpr string

	// KeySize is the fixed key length in bytes. For a numeric
	// index this must be 8, since the format stores an IEEE
	// double.
	KeySize uint16

	// KeyType selects character or numeric key comparison.
	KeyType uint16

	// Unique indexes keep only the first record for each key
	// value, matching dBASE's INDEX ON ... UNIQUE.
	Unique bool
}

// Index represents an open NDX index file.
type Index struct {
	rw io.ReadWriteSeeker

	keyExpr string
	keySize uint16
	keyType uint16
	unique  bool

	// keysPerPage is the maximum entry count a page can hold,
	// stored in the header at offset 14 and recomputed on create.
	keysPerPage uint16

	// recordSize is the on-disk size of one key record: the
	// lower-level pointer, the record number, and the key rounded
	// up to a multiple of four. Stored at header offset 18.
	recordSize uint32

	root      uint32
	pageCount uint32
}

// Entry is one index entry: a key and the record number it points
// at.
type Entry struct {
	Key   []byte
	Recno uint32
}

// KeyExpr returns the key expression recorded in the header.
func (ix *Index) KeyExpr() string { return ix.keyExpr }

// KeySize returns the fixed key width in bytes.
func (ix *Index) KeySize() uint16 { return ix.keySize }

// KeyType returns KeyTypeCharacter or KeyTypeNumeric.
func (ix *Index) KeyType() uint16 { return ix.keyType }

// Unique reports whether the index rejects duplicate keys.
func (ix *Index) Unique() bool { return ix.unique }

// KeysPerPage returns the maximum number of entries a page holds.
func (ix *Index) KeysPerPage() uint16 { return ix.keysPerPage }

// RecordSize returns the on-disk size of one key record.
func (ix *Index) RecordSize() uint32 { return ix.recordSize }

// keyRecordSize computes the on-disk entry size for a key width.
//
// The rule is 4 bytes of lower-level pointer, 4 bytes of record
// number, and the key rounded up to a multiple of four. Verified
// against the oracle for both a 10-byte character key, giving 20,
// and an 8-byte numeric key, giving 16.
func keyRecordSize(keySize uint16) uint32 {
	padded := (uint32(keySize) + 3) / 4 * 4
	return 4 + 4 + padded
}

// keysPerPage computes how many entries fit on a page.
//
// A page spends its first four bytes on the entry count, leaving
// the rest for records.
func keysPerPageFor(recordSize uint32) uint16 {
	return uint16((PageSize - 4) / recordSize)
}
