package mdx

import (
	"io"
	"os"
	"path/filepath"
	"testing"
)

type memFile struct {
	data []byte
	pos  int64
}

func (m *memFile) Read(p []byte) (int, error) {
	if m.pos >= int64(len(m.data)) {
		return 0, io.EOF
	}
	n := copy(p, m.data[m.pos:])
	m.pos += int64(n)
	return n, nil
}
func (m *memFile) Write(p []byte) (int, error) {
	end := m.pos + int64(len(p))
	if end > int64(len(m.data)) {
		g := make([]byte, end)
		copy(g, m.data)
		m.data = g
	}
	copy(m.data[m.pos:end], p)
	m.pos = end
	return len(p), nil
}
func (m *memFile) Seek(off int64, whence int) (int64, error) {
	switch whence {
	case 0:
		m.pos = off
	case 1:
		m.pos += off
	case 2:
		m.pos = int64(len(m.data)) + off
	}
	return m.pos, nil
}

func pad(s string, w int) []byte {
	k := make([]byte, w)
	for i := range k {
		k[i] = ' '
	}
	copy(k, s)
	return k
}

// TestReadsClipperMDX is the oracle test: 3 tags, 5 records each,
// generated by Borland dBASE 5.0, not Clipper — this is the
// vendor's own file rather than a generated oracle fixture, which
// is the strongest provenance available for this format.
func TestReadsClipperMDX(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("testdata", "ACCT_REC.MDX"))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	f, err := Open(&memFile{data: data})
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	if f.DataFile() != "ACCT_REC" {
		t.Errorf("DataFile = %q, want ACCT_REC", f.DataFile())
	}
	if len(f.Tags()) != 3 {
		t.Fatalf("got %d tags, want 3", len(f.Tags()))
	}

	cust, ok := f.Tag("CUST_ID")
	if !ok {
		t.Fatal("CUST_ID tag not found")
	}
	if cust.KeyType != KeyCharacter || cust.KeySize != 6 {
		t.Errorf("CUST_ID: type=%c size=%d, want C/6", cust.KeyType, cust.KeySize)
	}
	entries, err := f.TagEntries("CUST_ID")
	if err != nil {
		t.Fatalf("TagEntries(CUST_ID): %v", err)
	}
	want := []struct {
		key   string
		recno uint32
	}{{"A00001", 3}, {"B12345", 1}, {"C00001", 4}, {"C00002", 5}, {"L00002", 2}}
	if len(entries) != len(want) {
		t.Fatalf("got %d entries, want %d", len(entries), len(want))
	}
	for i, w := range want {
		if string(entries[i].Key) != w.key || entries[i].RecNo != w.recno {
			t.Errorf("entry %d = %q/%d, want %q/%d", i, entries[i].Key, entries[i].RecNo, w.key, w.recno)
		}
	}

	// Second character tag, cross-checking the stride derivation
	// against a different key width (10 vs 6).
	inv, ok := f.Tag("INVOICE_NO")
	if !ok {
		t.Fatal("INVOICE_NO tag not found")
	}
	if inv.KeySize != 10 {
		t.Errorf("INVOICE_NO KeySize = %d, want 10", inv.KeySize)
	}
	invEntries, err := f.TagEntries("INVOICE_NO")
	if err != nil {
		t.Fatalf("TagEntries(INVOICE_NO): %v", err)
	}
	if len(invEntries) != 5 {
		t.Fatalf("got %d INVOICE_NO entries, want 5", len(invEntries))
	}
	if string(invEntries[0].Key) != "A000018806" {
		t.Errorf("first INVOICE_NO entry = %q, want A000018806", invEntries[0].Key)
	}

	// Numeric tag is listed but not decoded.
	bal, ok := f.Tag("OLDBALANCE")
	if !ok {
		t.Fatal("OLDBALANCE tag not found")
	}
	if bal.KeyType != KeyNumeric {
		t.Errorf("OLDBALANCE type = %c, want N", bal.KeyType)
	}
}

func TestBuildAndReadRoundTrip(t *testing.T) {
	f2 := &memFile{}
	f, err := Create(f2, "CUSTOMER")
	if err != nil {
		t.Fatalf("Create: %v", err)
	}
	entries := []TagEntry{
		{Key: pad("ZULU", 6), RecNo: 1},
		{Key: pad("ALFA", 6), RecNo: 2},
		{Key: pad("MIKE", 6), RecNo: 3},
	}
	if err := f.AddTag("NAME", KeyCharacter, 6, entries, false); err != nil {
		t.Fatalf("AddTag: %v", err)
	}
	f2.pos = 0
	reopened, err := Open(f2)
	if err != nil {
		t.Fatalf("reopen: %v", err)
	}
	if len(reopened.Tags()) != 1 {
		t.Fatalf("got %d tags, want 1", len(reopened.Tags()))
	}
	got, err := reopened.TagEntries("NAME")
	if err != nil {
		t.Fatalf("TagEntries: %v", err)
	}
	want := []string{"ALFA  ", "MIKE  ", "ZULU  "}
	if len(got) != 3 {
		t.Fatalf("got %d entries, want 3", len(got))
	}
	for i, w := range want {
		if string(got[i].Key) != w {
			t.Errorf("entry %d = %q, want %q", i, got[i].Key, w)
		}
	}
}

func TestMultiTagBuild(t *testing.T) {
	f2 := &memFile{}
	f, _ := Create(f2, "ORDERS")
	f.AddTag("A", KeyCharacter, 4, []TagEntry{{Key: pad("B", 4), RecNo: 1}}, false)
	f.AddTag("B", KeyCharacter, 4, []TagEntry{{Key: pad("A", 4), RecNo: 2}}, false)
	f2.pos = 0
	r, err := Open(f2)
	if err != nil {
		t.Fatalf("reopen: %v", err)
	}
	if len(r.Tags()) != 2 {
		t.Fatalf("got %d tags, want 2", len(r.Tags()))
	}
	eb, err := r.TagEntries("B")
	if err != nil || len(eb) != 1 || eb[0].RecNo != 2 {
		t.Errorf("tag B entries wrong: %v %v", eb, err)
	}
}

// TestNumericKeyOracle reads OLDBALANCE from the real ACCT_REC.MDX
// (vendor-written, dBASE 5.0) and confirms every value decodes to
// the value that was actually written to the paired .DBF.
func TestNumericKeyOracle(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("testdata", "ACCT_REC.MDX"))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	f, err := Open(&memFile{data: data})
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	bal, ok := f.Tag("OLDBALANCE")
	if !ok {
		t.Fatal("OLDBALANCE tag not found")
	}
	if bal.KeyType != KeyNumeric {
		t.Fatalf("KeyType = %c, want N", bal.KeyType)
	}
	entries, err := f.TagEntries("OLDBALANCE")
	if err != nil {
		t.Fatalf("TagEntries: %v", err)
	}
	// Ground truth: the OLDBALANCE column as written in
	// ACCT_REC.DBF, keyed by record number.
	want := map[uint32]float64{1: 1000.00, 2: 350.00, 3: -200.00, 4: 0.00, 5: 125.00}
	if len(entries) != len(want) {
		t.Fatalf("got %d entries, want %d", len(entries), len(want))
	}
	// Entries come back in key (sorted) order; decode each and
	// match against ground truth by checking the value appears
	// with the right record number.
	seen := map[uint32]float64{}
	for _, e := range entries {
		v, err := DecodeNumericKey(e.Key)
		if err != nil {
			t.Fatalf("DecodeNumericKey(recno=%d): %v", e.RecNo, err)
		}
		seen[e.RecNo] = v
	}
	for recno, w := range want {
		got, ok := seen[recno]
		if !ok {
			t.Errorf("record %d missing from decoded entries", recno)
			continue
		}
		if got != w {
			t.Errorf("record %d: decoded %v, want %v", recno, got, w)
		}
	}
	// Sorted order must be numeric order (the whole point of the
	// type-aware comparator): -200, 0, 125, 350, 1000.
	wantOrder := []float64{-200, 0, 125, 350, 1000}
	for i, w := range wantOrder {
		v, _ := DecodeNumericKey(entries[i].Key)
		if v != w {
			t.Errorf("sorted position %d = %v, want %v (entries not in numeric order)", i, v, w)
		}
	}
}

// TestNumericKeyEncodeDecodeRoundTrip covers values beyond the
// oracle specimens, within the verified 4-significant-digit scope.
func TestNumericKeyEncodeDecodeRoundTrip(t *testing.T) {
	values := []float64{0, 1, -1, 202, 818, -818, 1000, 9999, -9999, 0.001, -0.001, 1234}
	for _, v := range values {
		enc, err := EncodeNumericKey(v)
		if err != nil {
			t.Fatalf("EncodeNumericKey(%v): %v", v, err)
		}
		got, err := DecodeNumericKey(enc)
		if err != nil {
			t.Fatalf("DecodeNumericKey: %v", err)
		}
		if got != v {
			t.Errorf("round trip %v -> %x -> %v", v, enc, got)
		}
	}
}

// TestNumericKeyRejectsUnverifiedPrecision guards the boundary:
// values needing more than 4 significant digits are refused
// rather than silently rounded.
func TestNumericKeyRejectsUnverifiedPrecision(t *testing.T) {
	if _, err := EncodeNumericKey(123.456); err == nil {
		t.Error("EncodeNumericKey(123.456) succeeded; want ErrNumericUnsupported (5 significant digits)")
	}
	if _, err := EncodeNumericKey(12345); err == nil {
		t.Error("EncodeNumericKey(12345) succeeded; want ErrNumericUnsupported (5 significant digits)")
	}
}

// TestBuildNumericTag exercises the write path end to end,
// including that sort order comes out numeric rather than
// byte-lexicographic — the case that would fail silently if
// AddTag still used bytes.Compare for Numeric tags.
func TestBuildNumericTag(t *testing.T) {
	f2 := &memFile{}
	f, _ := Create(f2, "AMOUNTS")
	values := []float64{100, -50, 0, -1000, 25, -25}
	entries := make([]TagEntry, len(values))
	for i, v := range values {
		key, err := EncodeNumericKey(v)
		if err != nil {
			t.Fatalf("EncodeNumericKey(%v): %v", v, err)
		}
		entries[i] = TagEntry{Key: key, RecNo: uint32(i + 1)}
	}
	if err := f.AddTag("AMT", KeyNumeric, 12, entries, false); err != nil {
		t.Fatalf("AddTag: %v", err)
	}
	f2.pos = 0
	r, err := Open(f2)
	if err != nil {
		t.Fatalf("reopen: %v", err)
	}
	got, err := r.TagEntries("AMT")
	if err != nil {
		t.Fatalf("TagEntries: %v", err)
	}
	want := []float64{-1000, -50, -25, 0, 25, 100}
	if len(got) != len(want) {
		t.Fatalf("got %d entries, want %d", len(got), len(want))
	}
	for i, w := range want {
		v, err := DecodeNumericKey(got[i].Key)
		if err != nil {
			t.Fatalf("DecodeNumericKey: %v", err)
		}
		if v != w {
			t.Errorf("position %d = %v, want %v — not in numeric order", i, v, w)
		}
	}
}

func TestTagNotFound(t *testing.T) {
	f, _ := Create(&memFile{}, "X")
	if _, err := f.TagEntries("NOPE"); err == nil {
		t.Error("TagEntries on missing tag succeeded")
	}
}
